# Generated by Django 5.2.8 on 2025-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('icon_code', models.CharField(help_text='Icon identifier (e.g., feature1, feature2)', max_length=50)),
                ('gradient', models.CharField(default='from-primary-500 to-primary-600', help_text='Tailwind gradient classes', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeaturesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Features We Provide', max_length=200)),
                ('title_ar', models.CharField(default='المميزات التي نقدمها', max_length=200)),
                ('subtitle_en', models.TextField(default='Everything you need for a complete learning experience')),
                ('subtitle_ar', models.TextField(default='كل ما تحتاجه لتجربة تعليمية كاملة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Features Section',
                'verbose_name_plural': 'Features Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Transform Your Learning Journey', max_length=200)),
                ('title_ar', models.CharField(default='حوّل رحلتك التعليمية', max_length=200)),
                ('subtitle_en', models.TextField(default='{PLATFORM_NAME} is your gateway to quality education, connecting students with expert teachers in a personalized learning environment.')),
                ('subtitle_ar', models.TextField(default='{PLATFORM_NAME} هو بوابتك للتعليم الجيد، يربط الطلاب بالمعلمين الخبراء في بيئة تعليمية مخصصة.')),
                ('description_en', models.TextField(default='Whether you are a school student, university student, or an educator, our platform provides the tools and resources you need to excel in your academic journey.')),
                ('description_ar', models.TextField(default='سواء كنت طالب مدرسة، طالب جامعة، أو معلم، منصتنا توفر الأدوات والموارد التي تحتاجها للتفوق في رحلتك الأكاديمية.')),
                ('cta_button_text_en', models.CharField(default='Get Started', max_length=50)),
                ('cta_button_text_ar', models.CharField(default='ابدأ الآن', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='Bait Al-Hikma', max_length=100)),
                ('name_ar', models.CharField(default='بيت الحكمة', max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('icon_code', models.CharField(help_text='Icon identifier', max_length=50)),
                ('gradient', models.CharField(default='from-primary-500 to-primary-600', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Reason',
                'verbose_name_plural': 'Why Choose Us Reasons',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Why Choose Us', max_length=200)),
                ('title_ar', models.CharField(default='لماذا تختارنا', max_length=200)),
                ('subtitle_en', models.TextField(default='Join thousands of students and teachers who trust {PLATFORM_NAME}')),
                ('subtitle_ar', models.TextField(default='انضم إلى آلاف الطلاب والمعلمين الذين يثقون بـ {PLATFORM_NAME}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('school_student', 'School Student'), ('university_student', 'University Student'), ('teacher', 'Teacher')], max_length=20, null=True),
        ),
    ]
