# Generated by Django 5.2.8 on 2025-11-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feature_featuressection_herosection_platformsettings_and_more'),
    ]

    operations = [
    ]
