# Generated by Django 5.2.8 on 2025-11-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_missing_user_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Maximum 150 words', max_length=1500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('both', 'Both')], default='ar', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course_type', models.CharField(choices=[('school', 'School'), ('university', 'University')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, help_text='Required for school courses', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, help_text='Required if course is for grade 11 or 12', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
