# Generated by Django 5.2.8 on 2025-11-22 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('publish', 'Publish'), ('unpublish', 'Unpublish'), ('delete', 'Delete')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason provided by teacher', null=True)),
                ('admin_note', models.TextField(blank=True, help_text='Admin note/reason for decision', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='api.course')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Approval Request',
                'verbose_name_plural': 'Course Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
