# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='for_university_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='for_school_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availability',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='availabilities', to='api.grade'),
        ),
    ]

