# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_availability_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(default=False, help_text='Whether this availability has been booked by a student'),
        ),
        migrations.AddField(
            model_name='availability',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

