# Generated by Django 5.2.8 on 2025-11-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_availability_add_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availability',
            name='unique_teacher_date_hour',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published')], default='draft', max_length=20),
        ),
        # Note: unique_together constraint removed - will be handled in 0009_availability_blocks
    ]
