# Generated by Django 5.2.8 on 2025-01-XX XX:XX

from django.db import migrations, models


def set_end_hour_from_start_hour(apps, schema_editor):
    """Set end_hour to start_hour + 1 for existing records"""
    Availability = apps.get_model('api', 'Availability')
    # Use order_by('id') to avoid default ordering that might reference old 'hour' field
    # At this point, 'hour' has been renamed to 'start_hour' in the database
    for availability in Availability.objects.all().order_by('id'):
        availability.end_hour = (availability.start_hour + 1) % 24
        availability.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20251123_0224'),
    ]

    operations = [
        # Remove unique_together constraint that references 'hour' before renaming
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='hour',
            new_name='start_hour',
        ),
        # Update Meta ordering to use start_hour instead of hour
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_hour'], 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='availability',
            name='end_hour',
            field=models.IntegerField(null=True, help_text='End hour in 24-hour format (0-23), exclusive (not included)'),
        ),
        migrations.RunPython(set_end_hour_from_start_hour),
        migrations.AlterField(
            model_name='availability',
            name='end_hour',
            field=models.IntegerField(help_text='End hour in 24-hour format (0-23), exclusive (not included)'),
        ),
        # Note: unique_teacher_date_hour constraint was already removed in 0008_remove_availability_unique_teacher_date_hour_and_more
    ]

