# Generated by Django 5.2.8 on 2025-11-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_availability_booking_fields'),
        ('api', '0008_remove_availability_unique_teacher_date_hour_and_more'),
    ]

    operations = [
    ]
