# Generated by Django 5.2.8 on 2025-11-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_availability_blocks'),
        ('api', '0009_merge_20251123_0224'),
    ]

    operations = [
    ]
