# Generated by Django 5.2.8 on 2025-11-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_question_quiz_alter_availability_start_hour_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='platform_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Platform commission percentage (e.g., 25.00 for 25%)', max_digits=5),
        ),
    ]
