# Generated by Django 5.2.8 on 2025-11-24 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_country_currency_code_country_currency_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLessonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.CharField(choices=[('university_student', 'University Student'), ('school_student', 'School Student')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per hour', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(blank=True, help_text='Required for school students', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_lesson_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Lesson Price',
                'verbose_name_plural': 'Private Lesson Prices',
                'ordering': ['-created_at'],
                'unique_together': {('teacher', 'student_type', 'subject', 'grade')},
            },
        ),
    ]
