# Generated by Django 5.2.8 on 2025-11-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='drm_key_id',
            field=models.CharField(blank=True, help_text='DRM encryption key ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='drm_manifest_url',
            field=models.URLField(blank=True, help_text='DRM manifest URL (DASH/HLS)', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='drm_playready_key',
            field=models.TextField(blank=True, help_text='PlayReady encryption key (base64)', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='drm_widevine_key',
            field=models.TextField(blank=True, help_text='Widevine encryption key (base64)', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_drm_encrypted',
            field=models.BooleanField(default=False, help_text='Whether this video is DRM encrypted'),
        ),
    ]
