# Generated by Django 5.2.8 on 2025-11-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_video_drm_key_id_video_drm_manifest_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='drm_key_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='drm_manifest_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='drm_playready_key',
        ),
        migrations.RemoveField(
            model_name='video',
            name='drm_widevine_key',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_drm_encrypted',
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(blank=True, help_text='Required for university courses', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Required for school courses', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grade'),
        ),
    ]
