# Generated by Django 5.2.8 on 2025-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_major_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects for university students', related_name='availabilities', to='api.subject'),
        ),
    ]
