# Generated by Django 5.2.8 on 2025-11-26 02:04

from django.db import migrations, models


def migrate_subject_to_subjects(apps, schema_editor):
    """Migrate data from old subject ForeignKey to new subjects ManyToMany"""
    Course = apps.get_model('api', 'Course')
    Subject = apps.get_model('api', 'Subject')
    
    for course in Course.objects.all():
        # Get the old subject if it exists
        if hasattr(course, 'subject') and course.subject:
            # Add the old subject to the new ManyToMany field
            course.subjects.add(course.subject)


def reverse_migrate_subjects_to_subject(apps, schema_editor):
    """Reverse migration - take first subject from ManyToMany and set as ForeignKey"""
    Course = apps.get_model('api', 'Course')
    
    for course in Course.objects.all():
        if hasattr(course, 'subjects') and course.subjects.exists():
            # This won't work in reverse as we're removing the field
            # But we need this function for the migration to be reversible
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_student_tasks_and_notes'),
    ]

    operations = [
        # First, add the new ManyToMany field (nullable initially)
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(help_text='Subjects for this course', related_name='courses', to='api.subject', blank=True),
        ),
        # Migrate data from old field to new field
        migrations.RunPython(migrate_subject_to_subjects, reverse_migrate_subjects_to_subject),
        # Now remove the old ForeignKey field
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
