# Generated by Django 5.2.8 on 2025-11-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_change_course_subject_to_manytomany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(help_text='Subjects for this course', related_name='courses', to='api.subject'),
        ),
    ]
