# Generated by Django 5.2.8 on 2025-11-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_major_from_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='tracks',
            field=models.ManyToManyField(blank=True, help_text='Tracks for school students (grades 11-12)', related_name='availabilities', to='api.track'),
        ),
        migrations.CreateModel(
            name='MajorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_subjects', to='api.major')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_subjects', to='api.subject')),
            ],
            options={
                'verbose_name': 'Major Subject',
                'verbose_name_plural': 'Major Subjects',
                'ordering': ['major', 'subject'],
                'unique_together': {('major', 'subject')},
            },
        ),
    ]
