# Generated by Django 5.2.8 on 2025-11-26 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_major_subject_and_tracks_to_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_enrolled', 'Not Enrolled'), ('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(blank=True, help_text='When student enrolled', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When student completed the course', null=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Course completion percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at', '-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
