# Generated by Django 5.2.8 on 2025-11-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_name_en',
            field=models.CharField(blank=True, help_text='Currency name in English (e.g., "Shakel", "Dinar")', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol or Arabic name (e.g., "شيكل")', max_length=10),
        ),
    ]
