# Generated by Django 5.2.8 on 2025-11-26 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_country_currency_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Number of correct answers')),
                ('total_questions', models.IntegerField(help_text='Total number of questions')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Score percentage', max_digits=5)),
                ('answers', models.JSONField(help_text='Student answers: {question_id: selected_option_index}')),
                ('results', models.JSONField(help_text='Question results: {question_id: {is_correct: bool, selected_option: int, correct_option: int}}')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz')], max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_completions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.video')),
            ],
            options={
                'verbose_name': 'Material Completion',
                'verbose_name_plural': 'Material Completions',
                'unique_together': {('student', 'quiz'), ('student', 'video')},
            },
        ),
    ]
