# Generated by Django 5.2.8 on 2025-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_quizattempt_materialcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue')], default='blue', help_text='Color for schedule organization (students only)', max_length=10),
        ),
    ]
