# Generated by Django 5.2.8 on 2025-11-26 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_color_to_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue')], default='blue', max_length=10)),
                ('date', models.DateField()),
                ('start_hour', models.IntegerField(help_text='Start hour in 24-hour format (0-23)')),
                ('end_hour', models.IntegerField(help_text='End hour in 24-hour format (0-23), exclusive (not included)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Schedule',
                'verbose_name_plural': 'Student Schedules',
                'ordering': ['date', 'start_hour'],
            },
        ),
    ]
