# Generated by Django 5.2.8 on 2025-11-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_todolist_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='private_lesson_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage for private lessons (e.g., 10.00 for 10%)', max_digits=5),
        ),
    ]
