# Generated by Django 5.2.8 on 2025-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_private_lesson_commission_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Platform logo image', null=True, upload_to='platform_logos/'),
        ),
    ]
