# Generated by Django 5.2.8 on 2025-11-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_change_logo_url_to_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('study_minutes', models.PositiveIntegerField(help_text='Study duration in minutes')),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Break duration in minutes (0 means no break)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_timers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Timer',
                'verbose_name_plural': 'Study Timers',
                'ordering': ['-created_at'],
            },
        ),
    ]
