# Generated by Django 5.2.8 on 2025-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_study_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='About Us', max_length=200)),
                ('title_ar', models.CharField(default='من نحن', max_length=200)),
                ('subtitle_en', models.TextField(default='Learn more about our mission and vision')),
                ('subtitle_ar', models.TextField(default='تعرف على المزيد حول مهمتنا ورؤيتنا')),
                ('mission_title_en', models.CharField(default='Our Mission', max_length=200)),
                ('mission_title_ar', models.CharField(default='مهمتنا', max_length=200)),
                ('mission_content_en', models.TextField(default='We are dedicated to providing quality education and connecting students with expert teachers in a personalized learning environment. Our platform empowers learners to excel in their academic journey through innovative tools and comprehensive resources.')),
                ('mission_content_ar', models.TextField(default='نحن ملتزمون بتقديم تعليم عالي الجودة وربط الطلاب بالمعلمين الخبراء في بيئة تعليمية مخصصة. تمكّن منصتنا المتعلمين من التفوق في رحلتهم الأكاديمية من خلال أدوات مبتكرة وموارد شاملة.')),
                ('vision_title_en', models.CharField(default='Our Vision', max_length=200)),
                ('vision_title_ar', models.CharField(default='رؤيتنا', max_length=200)),
                ('vision_content_en', models.TextField(default='To become the leading educational platform that transforms how students learn and teachers teach, making quality education accessible to everyone.')),
                ('vision_content_ar', models.TextField(default='أن نصبح المنصة التعليمية الرائدة التي تحول طريقة تعلم الطلاب وطريقة تدريس المعلمين، مما يجعل التعليم عالي الجودة في متناول الجميع.')),
                ('why_choose_us_title_en', models.CharField(default='Why Choose Us', max_length=200)),
                ('why_choose_us_title_ar', models.CharField(default='لماذا تختارنا', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='PreviousExamsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Previous Exams', max_length=200)),
                ('title_ar', models.CharField(default='الامتحانات السابقة', max_length=200)),
                ('subtitle_en', models.TextField(default='Prepare for your exams with AI-powered predictions')),
                ('subtitle_ar', models.TextField(default='استعد لامتحاناتك مع توقعات مدعومة بالذكاء الاصطناعي')),
                ('available_for_all_title_en', models.CharField(default='Available for All Students', max_length=200)),
                ('available_for_all_title_ar', models.CharField(default='متاح لجميع الطلاب', max_length=200)),
                ('available_for_all_content_en', models.TextField(default='Previous exams are available for all grades and university students. After signing up, you will see previous exams in your dashboard that help you prepare well for your upcoming tests.')),
                ('available_for_all_content_ar', models.TextField(default='الامتحانات السابقة متاحة لجميع الصفوف وطلاب الجامعة. بعد التسجيل، سترى الامتحانات السابقة في لوحة التحكم الخاصة بك والتي تساعدك على الاستعداد جيداً لاختباراتك القادمة.')),
                ('ai_prediction_title_en', models.CharField(default='AI-Powered Question Prediction (Grade 12 Only)', max_length=200)),
                ('ai_prediction_title_ar', models.CharField(default='التنبؤ بالأسئلة المدعوم بالذكاء الاصطناعي (الصف الثاني عشر فقط)', max_length=200)),
                ('ai_prediction_content_en', models.TextField(default='Our advanced AI model is exclusively available for Grade 12 students across all tracks. The AI analyzes past exam patterns and curriculum to predict the most likely questions for all your subjects, helping you get ahead of your exams with intelligent question forecasting tailored to your track.')),
                ('ai_prediction_content_ar', models.TextField(default='نموذج الذكاء الاصطناعي المتقدم لدينا متاح حصرياً لطلاب الصف الثاني عشر في جميع المسارات. يحلل الذكاء الاصطناعي أنماط الامتحانات السابقة والمنهج الدراسي للتنبؤ بالأسئلة الأكثر احتمالاً لجميع موادك، مما يساعدك على التقدم في امتحاناتك مع التنبؤ الذكي بالأسئلة المصمم خصيصاً لمسارك.')),
                ('ai_note_en', models.TextField(default='The AI prediction feature is exclusively available for Grade 12 students. All other grades and university students have access to previous exam papers.')),
                ('ai_note_ar', models.TextField(default='ميزة التنبؤ بالذكاء الاصطناعي متاحة حصرياً لطلاب الصف الثاني عشر. جميع الصفوف الأخرى وطلاب الجامعة لديهم وصول إلى أوراق الامتحانات السابقة.')),
                ('real_time_practice_title_en', models.CharField(default='Real-Time Exam Practice', max_length=200)),
                ('real_time_practice_title_ar', models.CharField(default='ممارسة الامتحان في الوقت الفعلي', max_length=200)),
                ('real_time_practice_content_en', models.TextField(default="Practice with timed exams that simulate real testing conditions. This helps you build confidence, improve time management, and ensures you're well-prepared for your actual exam day.")),
                ('real_time_practice_content_ar', models.TextField(default='تدرب مع امتحانات مؤقتة تحاكي ظروف الاختبار الحقيقية. يساعدك هذا على بناء الثقة وتحسين إدارة الوقت وضمان استعدادك الجيد ليوم الامتحان الفعلي.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Previous Exams Section',
                'verbose_name_plural': 'Previous Exams Section',
            },
        ),
    ]
