# Generated by Django 5.2.8 on 2025-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_aboutsection_previousexamssection'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default='+1', help_text='Phone country code (e.g., +972, +962)', max_length=10),
        ),
    ]
