# Generated by Django 5.2.8 on 2025-12-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_country_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(default='🏳️', help_text='Country flag emoji (e.g., 🇵🇸, 🇯🇴)', max_length=10),
        ),
    ]
