# Generated by Django 5.2.8 on 2025-11-27 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0030_add_study_timer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid by student', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Platform commission percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Platform commission amount', max_digits=10)),
                ('teacher_payout_amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to teacher (after commission)', max_digits=10)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('wallet', 'Wallet')], default='bank_transfer', help_text='Payment method used', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=255, null=True, unique=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Full response from payment gateway', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevent duplicate payments', max_length=255, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When payment was verified', null=True)),
                ('verification_method', models.CharField(blank=True, help_text='How payment was verified (webhook, api_call, manual, test)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(blank=True, help_text='The lesson slot that was booked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.availability')),
                ('student', models.ForeignKey(help_text='Student who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(help_text='Teacher receiving the payment', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to teacher', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payout was completed (money sent)', null=True)),
                ('transfer_reference', models.CharField(blank=True, help_text='Bank transfer reference number', max_length=255, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the transfer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, help_text='Admin who marked this as paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_payouts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(help_text='The payment this payout is for', on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='payments.payment')),
                ('teacher', models.ForeignKey(help_text='Teacher receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='Name of the bank', max_length=200)),
                ('account_number', models.CharField(help_text='Bank account number', max_length=100)),
                ('account_holder_name', models.CharField(help_text='Name on the bank account', max_length=200)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number (IBAN)', max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='Bank branch name', max_length=200, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether admin has verified this information')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When this information was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Payment Information',
                'verbose_name_plural': 'Teacher Payment Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', '-created_at'], name='payments_pa_student_bac7de_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['teacher', '-created_at'], name='payments_pa_teacher_76c6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['teacher', 'status'], name='payments_pa_teacher_e61071_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_b1a303_idx'),
        ),
    ]
